// flow-typed signature: 04fd876bc09bc933b92fda3b0d1904a9
// flow-typed version: <<STUB>>/babel-istanbul_v^0.11.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-istanbul/lib/assets/sorter' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/assets/vendor/prettify' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/cli' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/collector' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/check-coverage' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/common/run-with-cover' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/cover' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/help' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/index' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/instrument' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/report' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/command/test' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/config' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/hook' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/instrumenter' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/object-utils' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/register-plugins' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/clover' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/cobertura' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/common/defaults' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/html' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/index' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/json-summary' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/json' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/lcov' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/lcovonly' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/none' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/teamcity' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/text-lcov' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/text-summary' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/report/text' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/reporter' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/store/fslookup' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/store/index' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/store/memory' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/store/tmp' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/factory' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/file-matcher' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/file-writer' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/help-formatter' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/input-error' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/insertion-text' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/meta' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/tree-summarizer' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/writer' {
  declare module.exports: any;
}

declare module 'babel-istanbul/lib/util/yui-load-hook' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-istanbul/index' {
  declare module.exports: $Exports<'babel-istanbul'>;
}
declare module 'babel-istanbul/index.js' {
  declare module.exports: $Exports<'babel-istanbul'>;
}
declare module 'babel-istanbul/lib/assets/sorter.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/assets/sorter'>;
}
declare module 'babel-istanbul/lib/assets/vendor/prettify.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/assets/vendor/prettify'>;
}
declare module 'babel-istanbul/lib/cli.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/cli'>;
}
declare module 'babel-istanbul/lib/collector.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/collector'>;
}
declare module 'babel-istanbul/lib/command/check-coverage.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/check-coverage'>;
}
declare module 'babel-istanbul/lib/command/common/run-with-cover.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/common/run-with-cover'>;
}
declare module 'babel-istanbul/lib/command/cover.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/cover'>;
}
declare module 'babel-istanbul/lib/command/help.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/help'>;
}
declare module 'babel-istanbul/lib/command/index.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/index'>;
}
declare module 'babel-istanbul/lib/command/instrument.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/instrument'>;
}
declare module 'babel-istanbul/lib/command/report.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/report'>;
}
declare module 'babel-istanbul/lib/command/test.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/command/test'>;
}
declare module 'babel-istanbul/lib/config.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/config'>;
}
declare module 'babel-istanbul/lib/hook.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/hook'>;
}
declare module 'babel-istanbul/lib/instrumenter.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/instrumenter'>;
}
declare module 'babel-istanbul/lib/object-utils.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/object-utils'>;
}
declare module 'babel-istanbul/lib/register-plugins.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/register-plugins'>;
}
declare module 'babel-istanbul/lib/report/clover.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/clover'>;
}
declare module 'babel-istanbul/lib/report/cobertura.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/cobertura'>;
}
declare module 'babel-istanbul/lib/report/common/defaults.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/common/defaults'>;
}
declare module 'babel-istanbul/lib/report/html.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/html'>;
}
declare module 'babel-istanbul/lib/report/index.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/index'>;
}
declare module 'babel-istanbul/lib/report/json-summary.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/json-summary'>;
}
declare module 'babel-istanbul/lib/report/json.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/json'>;
}
declare module 'babel-istanbul/lib/report/lcov.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/lcov'>;
}
declare module 'babel-istanbul/lib/report/lcovonly.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/lcovonly'>;
}
declare module 'babel-istanbul/lib/report/none.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/none'>;
}
declare module 'babel-istanbul/lib/report/teamcity.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/teamcity'>;
}
declare module 'babel-istanbul/lib/report/text-lcov.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/text-lcov'>;
}
declare module 'babel-istanbul/lib/report/text-summary.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/text-summary'>;
}
declare module 'babel-istanbul/lib/report/text.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/report/text'>;
}
declare module 'babel-istanbul/lib/reporter.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/reporter'>;
}
declare module 'babel-istanbul/lib/store/fslookup.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/store/fslookup'>;
}
declare module 'babel-istanbul/lib/store/index.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/store/index'>;
}
declare module 'babel-istanbul/lib/store/memory.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/store/memory'>;
}
declare module 'babel-istanbul/lib/store/tmp.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/store/tmp'>;
}
declare module 'babel-istanbul/lib/util/factory.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/factory'>;
}
declare module 'babel-istanbul/lib/util/file-matcher.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/file-matcher'>;
}
declare module 'babel-istanbul/lib/util/file-writer.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/file-writer'>;
}
declare module 'babel-istanbul/lib/util/help-formatter.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/help-formatter'>;
}
declare module 'babel-istanbul/lib/util/input-error.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/input-error'>;
}
declare module 'babel-istanbul/lib/util/insertion-text.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/insertion-text'>;
}
declare module 'babel-istanbul/lib/util/meta.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/meta'>;
}
declare module 'babel-istanbul/lib/util/tree-summarizer.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/tree-summarizer'>;
}
declare module 'babel-istanbul/lib/util/writer.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/writer'>;
}
declare module 'babel-istanbul/lib/util/yui-load-hook.js' {
  declare module.exports: $Exports<'babel-istanbul/lib/util/yui-load-hook'>;
}
