// flow-typed signature: 511ccee6eb842e1d1b61e791ff6051db
// flow-typed version: <<STUB>>/inline-style-prefixer_v^3.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inline-style-prefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'inline-style-prefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inline-style-prefixer/dynamic/createPrefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/dynamicData' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/crossFade' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/cursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/filter' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/imageSet' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/dynamic/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/generateDynamicPrefixMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/generatePluginList' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/generateStaticPrefixMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/maps/pluginMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/generator/maps/propertyMap' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/createPrefixer' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/calc' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/crossFade' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/cursor' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/filter' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/flex' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/flexboxIE' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/flexboxOld' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/gradient' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/imageSet' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/index' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/position' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/sizing' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/plugins/transition' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/static/staticData' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/addNewValuesOnly' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/capitalizeString' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/getBrowserInformation' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/getPrefixedKeyframes' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/getPrefixedValue' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/isObject' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/prefixProperty' {
  declare module.exports: any;
}

declare module 'inline-style-prefixer/utils/prefixValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inline-style-prefixer/dynamic/createPrefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/createPrefixer'>;
}
declare module 'inline-style-prefixer/dynamic/dynamicData.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/dynamicData'>;
}
declare module 'inline-style-prefixer/dynamic/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/index'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/calc'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/crossFade.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/crossFade'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/cursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/cursor'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/filter.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/filter'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/flex'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/gradient'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/imageSet.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/imageSet'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/index'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/position'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/sizing'>;
}
declare module 'inline-style-prefixer/dynamic/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/dynamic/plugins/transition'>;
}
declare module 'inline-style-prefixer/generator/generateDynamicPrefixMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/generateDynamicPrefixMap'>;
}
declare module 'inline-style-prefixer/generator/generatePluginList.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/generatePluginList'>;
}
declare module 'inline-style-prefixer/generator/generateStaticPrefixMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/generateStaticPrefixMap'>;
}
declare module 'inline-style-prefixer/generator/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/index'>;
}
declare module 'inline-style-prefixer/generator/maps/pluginMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/maps/pluginMap'>;
}
declare module 'inline-style-prefixer/generator/maps/propertyMap.js' {
  declare module.exports: $Exports<'inline-style-prefixer/generator/maps/propertyMap'>;
}
declare module 'inline-style-prefixer/static/createPrefixer.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/createPrefixer'>;
}
declare module 'inline-style-prefixer/static/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/index'>;
}
declare module 'inline-style-prefixer/static/plugins/calc.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/calc'>;
}
declare module 'inline-style-prefixer/static/plugins/crossFade.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/crossFade'>;
}
declare module 'inline-style-prefixer/static/plugins/cursor.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/cursor'>;
}
declare module 'inline-style-prefixer/static/plugins/filter.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/filter'>;
}
declare module 'inline-style-prefixer/static/plugins/flex.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/flex'>;
}
declare module 'inline-style-prefixer/static/plugins/flexboxIE.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/flexboxIE'>;
}
declare module 'inline-style-prefixer/static/plugins/flexboxOld.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/flexboxOld'>;
}
declare module 'inline-style-prefixer/static/plugins/gradient.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/gradient'>;
}
declare module 'inline-style-prefixer/static/plugins/imageSet.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/imageSet'>;
}
declare module 'inline-style-prefixer/static/plugins/index.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/index'>;
}
declare module 'inline-style-prefixer/static/plugins/position.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/position'>;
}
declare module 'inline-style-prefixer/static/plugins/sizing.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/sizing'>;
}
declare module 'inline-style-prefixer/static/plugins/transition.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/plugins/transition'>;
}
declare module 'inline-style-prefixer/static/staticData.js' {
  declare module.exports: $Exports<'inline-style-prefixer/static/staticData'>;
}
declare module 'inline-style-prefixer/utils/addNewValuesOnly.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/addNewValuesOnly'>;
}
declare module 'inline-style-prefixer/utils/capitalizeString.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/capitalizeString'>;
}
declare module 'inline-style-prefixer/utils/getBrowserInformation.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/getBrowserInformation'>;
}
declare module 'inline-style-prefixer/utils/getPrefixedKeyframes.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/getPrefixedKeyframes'>;
}
declare module 'inline-style-prefixer/utils/getPrefixedValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/getPrefixedValue'>;
}
declare module 'inline-style-prefixer/utils/isObject.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/isObject'>;
}
declare module 'inline-style-prefixer/utils/prefixProperty.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/prefixProperty'>;
}
declare module 'inline-style-prefixer/utils/prefixValue.js' {
  declare module.exports: $Exports<'inline-style-prefixer/utils/prefixValue'>;
}
