// flow-typed signature: 0953d9baac8251cc38f40d1011955980
// flow-typed version: <<STUB>>/karma-sinon-chai_v^1.2.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-sinon-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-sinon-chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-sinon-chai/chai-adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-sinon-chai/chai-adapter.js' {
  declare module.exports: $Exports<'karma-sinon-chai/chai-adapter'>;
}
declare module 'karma-sinon-chai/index' {
  declare module.exports: $Exports<'karma-sinon-chai'>;
}
declare module 'karma-sinon-chai/index.js' {
  declare module.exports: $Exports<'karma-sinon-chai'>;
}
