// flow-typed signature: 9b5b1885bf45d4adf8ce0d3ca9ab51b1
// flow-typed version: <<STUB>>/karma-rollup-preprocessor_v^3.0.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-rollup-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-rollup-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-rollup-preprocessor/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/lib/index' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/helper' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-rollup-preprocessor/karma.conf.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/karma.conf'>;
}
declare module 'karma-rollup-preprocessor/lib/index.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/lib/index'>;
}
declare module 'karma-rollup-preprocessor/test/helper.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/helper'>;
}
declare module 'karma-rollup-preprocessor/test/main.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/main'>;
}
