// flow-typed signature: 2d99e7d6377a0ac83377b9ad4ef0d586
// flow-typed version: <<STUB>>/lazyimg_v^0.1.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lazyimg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lazyimg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lazyimg/src/adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lazyimg/src/adapter.js' {
  declare module.exports: $Exports<'lazyimg/src/adapter'>;
}
