// flow-typed signature: ce0c870eb1fe7d632753dedcd93d9cb7
// flow-typed version: <<STUB>>/modals_v^0.1.6/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'modals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modals/build/modal' {
  declare module.exports: any;
}

declare module 'modals/gulpfile' {
  declare module.exports: any;
}

declare module 'modals/src/alert' {
  declare module.exports: any;
}

declare module 'modals/src/confirm' {
  declare module.exports: any;
}

declare module 'modals/src/index' {
  declare module.exports: any;
}

declare module 'modals/src/modal' {
  declare module.exports: any;
}

declare module 'modals/src/prompt' {
  declare module.exports: any;
}

declare module 'modals/src/toast' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modals/build/modal.js' {
  declare module.exports: $Exports<'modals/build/modal'>;
}
declare module 'modals/gulpfile.js' {
  declare module.exports: $Exports<'modals/gulpfile'>;
}
declare module 'modals/src/alert.js' {
  declare module.exports: $Exports<'modals/src/alert'>;
}
declare module 'modals/src/confirm.js' {
  declare module.exports: $Exports<'modals/src/confirm'>;
}
declare module 'modals/src/index.js' {
  declare module.exports: $Exports<'modals/src/index'>;
}
declare module 'modals/src/modal.js' {
  declare module.exports: $Exports<'modals/src/modal'>;
}
declare module 'modals/src/prompt.js' {
  declare module.exports: $Exports<'modals/src/prompt'>;
}
declare module 'modals/src/toast.js' {
  declare module.exports: $Exports<'modals/src/toast'>;
}
