// flow-typed signature: 2c10ff52ce02274157dba92fd2a8a434
// flow-typed version: <<STUB>>/nightwatch_v^0.9.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightwatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightwatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightwatch/bin/runner' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/custom-commands/hasOnBeforeUnload' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/globalsModule' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/mocha/github' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/mocha/googleDemoTest' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/pages/home' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/pages/searchResults' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/digg' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/github/github' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/google' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/google/googleDemoTest' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/googlePageObject' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/nightwatch' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/tests/onbeforeunload' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/unittests/demoTestAsync' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/unittests/testUtils' {
  declare module.exports: any;
}

declare module 'nightwatch/examples/unittests/testUtilsWithChai' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/attributeContains' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/attributeEquals' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/containsText' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/cssClassNotPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/cssClassPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/cssProperty' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/elementNotPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/elementPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/hidden' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/title' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/urlContains' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/urlEquals' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/value' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/valueContains' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/assertions/visible' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/_locateStrategy' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/end' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/pause' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/perform' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/useCss' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/useRecursion' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/client-commands/useXpath' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/_elementByRecursion' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/_elementsByRecursion' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/_waitForElement' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/waitForElementNotPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/waitForElementNotVisible' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/waitForElementPresent' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/element-commands/waitForElementVisible' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/_baseAssertion' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/attribute' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/css' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/enabled' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/present' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/selected' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/text' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/type' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/value' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/expect/visible' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/api/protocol' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/core/api' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/core/assertion' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/core/queue' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/http/request' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/index' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/page-object/command-wrapper' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/page-object/element' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/page-object/page-utils' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/page-object/page' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/page-object/section' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/cli/child-process' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/cli/cli' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/cli/clirunner' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/cli/errorhandler' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/clientmanager' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/filematcher' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/module' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/reporter' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/reporters/junit' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/run' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/selenium' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/testcase' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/testsuite' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/runner/walk' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/util/logger' {
  declare module.exports: any;
}

declare module 'nightwatch/lib/util/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightwatch/bin/runner.js' {
  declare module.exports: $Exports<'nightwatch/bin/runner'>;
}
declare module 'nightwatch/examples/custom-commands/hasOnBeforeUnload.js' {
  declare module.exports: $Exports<'nightwatch/examples/custom-commands/hasOnBeforeUnload'>;
}
declare module 'nightwatch/examples/globalsModule.js' {
  declare module.exports: $Exports<'nightwatch/examples/globalsModule'>;
}
declare module 'nightwatch/examples/mocha/github.js' {
  declare module.exports: $Exports<'nightwatch/examples/mocha/github'>;
}
declare module 'nightwatch/examples/mocha/googleDemoTest.js' {
  declare module.exports: $Exports<'nightwatch/examples/mocha/googleDemoTest'>;
}
declare module 'nightwatch/examples/pages/home.js' {
  declare module.exports: $Exports<'nightwatch/examples/pages/home'>;
}
declare module 'nightwatch/examples/pages/searchResults.js' {
  declare module.exports: $Exports<'nightwatch/examples/pages/searchResults'>;
}
declare module 'nightwatch/examples/tests/digg.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/digg'>;
}
declare module 'nightwatch/examples/tests/github/github.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/github/github'>;
}
declare module 'nightwatch/examples/tests/google.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/google'>;
}
declare module 'nightwatch/examples/tests/google/googleDemoTest.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/google/googleDemoTest'>;
}
declare module 'nightwatch/examples/tests/googlePageObject.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/googlePageObject'>;
}
declare module 'nightwatch/examples/tests/nightwatch.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/nightwatch'>;
}
declare module 'nightwatch/examples/tests/onbeforeunload.js' {
  declare module.exports: $Exports<'nightwatch/examples/tests/onbeforeunload'>;
}
declare module 'nightwatch/examples/unittests/demoTestAsync.js' {
  declare module.exports: $Exports<'nightwatch/examples/unittests/demoTestAsync'>;
}
declare module 'nightwatch/examples/unittests/testUtils.js' {
  declare module.exports: $Exports<'nightwatch/examples/unittests/testUtils'>;
}
declare module 'nightwatch/examples/unittests/testUtilsWithChai.js' {
  declare module.exports: $Exports<'nightwatch/examples/unittests/testUtilsWithChai'>;
}
declare module 'nightwatch/index' {
  declare module.exports: $Exports<'nightwatch'>;
}
declare module 'nightwatch/index.js' {
  declare module.exports: $Exports<'nightwatch'>;
}
declare module 'nightwatch/lib/api/assertions/attributeContains.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/attributeContains'>;
}
declare module 'nightwatch/lib/api/assertions/attributeEquals.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/attributeEquals'>;
}
declare module 'nightwatch/lib/api/assertions/containsText.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/containsText'>;
}
declare module 'nightwatch/lib/api/assertions/cssClassNotPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/cssClassNotPresent'>;
}
declare module 'nightwatch/lib/api/assertions/cssClassPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/cssClassPresent'>;
}
declare module 'nightwatch/lib/api/assertions/cssProperty.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/cssProperty'>;
}
declare module 'nightwatch/lib/api/assertions/elementNotPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/elementNotPresent'>;
}
declare module 'nightwatch/lib/api/assertions/elementPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/elementPresent'>;
}
declare module 'nightwatch/lib/api/assertions/hidden.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/hidden'>;
}
declare module 'nightwatch/lib/api/assertions/title.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/title'>;
}
declare module 'nightwatch/lib/api/assertions/urlContains.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/urlContains'>;
}
declare module 'nightwatch/lib/api/assertions/urlEquals.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/urlEquals'>;
}
declare module 'nightwatch/lib/api/assertions/value.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/value'>;
}
declare module 'nightwatch/lib/api/assertions/valueContains.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/valueContains'>;
}
declare module 'nightwatch/lib/api/assertions/visible.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/assertions/visible'>;
}
declare module 'nightwatch/lib/api/client-commands.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands'>;
}
declare module 'nightwatch/lib/api/client-commands/_locateStrategy.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/_locateStrategy'>;
}
declare module 'nightwatch/lib/api/client-commands/end.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/end'>;
}
declare module 'nightwatch/lib/api/client-commands/pause.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/pause'>;
}
declare module 'nightwatch/lib/api/client-commands/perform.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/perform'>;
}
declare module 'nightwatch/lib/api/client-commands/useCss.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/useCss'>;
}
declare module 'nightwatch/lib/api/client-commands/useRecursion.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/useRecursion'>;
}
declare module 'nightwatch/lib/api/client-commands/useXpath.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/client-commands/useXpath'>;
}
declare module 'nightwatch/lib/api/element-commands.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands'>;
}
declare module 'nightwatch/lib/api/element-commands/_elementByRecursion.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/_elementByRecursion'>;
}
declare module 'nightwatch/lib/api/element-commands/_elementsByRecursion.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/_elementsByRecursion'>;
}
declare module 'nightwatch/lib/api/element-commands/_waitForElement.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/_waitForElement'>;
}
declare module 'nightwatch/lib/api/element-commands/waitForElementNotPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/waitForElementNotPresent'>;
}
declare module 'nightwatch/lib/api/element-commands/waitForElementNotVisible.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/waitForElementNotVisible'>;
}
declare module 'nightwatch/lib/api/element-commands/waitForElementPresent.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/waitForElementPresent'>;
}
declare module 'nightwatch/lib/api/element-commands/waitForElementVisible.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/element-commands/waitForElementVisible'>;
}
declare module 'nightwatch/lib/api/expect.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect'>;
}
declare module 'nightwatch/lib/api/expect/_baseAssertion.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/_baseAssertion'>;
}
declare module 'nightwatch/lib/api/expect/attribute.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/attribute'>;
}
declare module 'nightwatch/lib/api/expect/css.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/css'>;
}
declare module 'nightwatch/lib/api/expect/enabled.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/enabled'>;
}
declare module 'nightwatch/lib/api/expect/present.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/present'>;
}
declare module 'nightwatch/lib/api/expect/selected.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/selected'>;
}
declare module 'nightwatch/lib/api/expect/text.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/text'>;
}
declare module 'nightwatch/lib/api/expect/type.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/type'>;
}
declare module 'nightwatch/lib/api/expect/value.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/value'>;
}
declare module 'nightwatch/lib/api/expect/visible.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/expect/visible'>;
}
declare module 'nightwatch/lib/api/protocol.js' {
  declare module.exports: $Exports<'nightwatch/lib/api/protocol'>;
}
declare module 'nightwatch/lib/core/api.js' {
  declare module.exports: $Exports<'nightwatch/lib/core/api'>;
}
declare module 'nightwatch/lib/core/assertion.js' {
  declare module.exports: $Exports<'nightwatch/lib/core/assertion'>;
}
declare module 'nightwatch/lib/core/queue.js' {
  declare module.exports: $Exports<'nightwatch/lib/core/queue'>;
}
declare module 'nightwatch/lib/http/request.js' {
  declare module.exports: $Exports<'nightwatch/lib/http/request'>;
}
declare module 'nightwatch/lib/index.js' {
  declare module.exports: $Exports<'nightwatch/lib/index'>;
}
declare module 'nightwatch/lib/page-object/command-wrapper.js' {
  declare module.exports: $Exports<'nightwatch/lib/page-object/command-wrapper'>;
}
declare module 'nightwatch/lib/page-object/element.js' {
  declare module.exports: $Exports<'nightwatch/lib/page-object/element'>;
}
declare module 'nightwatch/lib/page-object/page-utils.js' {
  declare module.exports: $Exports<'nightwatch/lib/page-object/page-utils'>;
}
declare module 'nightwatch/lib/page-object/page.js' {
  declare module.exports: $Exports<'nightwatch/lib/page-object/page'>;
}
declare module 'nightwatch/lib/page-object/section.js' {
  declare module.exports: $Exports<'nightwatch/lib/page-object/section'>;
}
declare module 'nightwatch/lib/runner/cli/child-process.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/cli/child-process'>;
}
declare module 'nightwatch/lib/runner/cli/cli.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/cli/cli'>;
}
declare module 'nightwatch/lib/runner/cli/clirunner.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/cli/clirunner'>;
}
declare module 'nightwatch/lib/runner/cli/errorhandler.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/cli/errorhandler'>;
}
declare module 'nightwatch/lib/runner/clientmanager.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/clientmanager'>;
}
declare module 'nightwatch/lib/runner/filematcher.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/filematcher'>;
}
declare module 'nightwatch/lib/runner/module.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/module'>;
}
declare module 'nightwatch/lib/runner/reporter.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/reporter'>;
}
declare module 'nightwatch/lib/runner/reporters/junit.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/reporters/junit'>;
}
declare module 'nightwatch/lib/runner/run.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/run'>;
}
declare module 'nightwatch/lib/runner/selenium.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/selenium'>;
}
declare module 'nightwatch/lib/runner/testcase.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/testcase'>;
}
declare module 'nightwatch/lib/runner/testsuite.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/testsuite'>;
}
declare module 'nightwatch/lib/runner/walk.js' {
  declare module.exports: $Exports<'nightwatch/lib/runner/walk'>;
}
declare module 'nightwatch/lib/util/logger.js' {
  declare module.exports: $Exports<'nightwatch/lib/util/logger'>;
}
declare module 'nightwatch/lib/util/utils.js' {
  declare module.exports: $Exports<'nightwatch/lib/util/utils'>;
}
