// flow-typed signature: ffee129c2c2545168f37519a266d3609
// flow-typed version: <<STUB>>/rollup-plugin-postcss_v^0.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-postcss/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-postcss/index' {
  declare module.exports: $Exports<'rollup-plugin-postcss'>;
}
declare module 'rollup-plugin-postcss/index.js' {
  declare module.exports: $Exports<'rollup-plugin-postcss'>;
}
declare module 'rollup-plugin-postcss/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-postcss/src/index'>;
}
