// flow-typed signature: e3657500c54b43bf9776c7b33d409899
// flow-typed version: <<STUB>>/rollup-plugin-flow-no-whitespace_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-flow-no-whitespace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-flow-no-whitespace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rollup-plugin-flow-no-whitespace/index' {
  declare module.exports: $Exports<'rollup-plugin-flow-no-whitespace'>;
}
declare module 'rollup-plugin-flow-no-whitespace/index.js' {
  declare module.exports: $Exports<'rollup-plugin-flow-no-whitespace'>;
}
