// flow-typed signature: 07a43208e87ce65dea47f3bb8ce1805d
// flow-typed version: <<STUB>>/vue-loader_v^11.3.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-loader/lib/component-normalizer' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/parser' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/selector' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/index' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/load-postcss-config' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/plugins/scope-id' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/plugins/trim' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/index' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/modules/transform-require' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/preprocessor' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/utils/gen-id' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/utils/normalize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-loader/index' {
  declare module.exports: $Exports<'vue-loader'>;
}
declare module 'vue-loader/index.js' {
  declare module.exports: $Exports<'vue-loader'>;
}
declare module 'vue-loader/lib/component-normalizer.js' {
  declare module.exports: $Exports<'vue-loader/lib/component-normalizer'>;
}
declare module 'vue-loader/lib/loader.js' {
  declare module.exports: $Exports<'vue-loader/lib/loader'>;
}
declare module 'vue-loader/lib/parser.js' {
  declare module.exports: $Exports<'vue-loader/lib/parser'>;
}
declare module 'vue-loader/lib/selector.js' {
  declare module.exports: $Exports<'vue-loader/lib/selector'>;
}
declare module 'vue-loader/lib/style-compiler/index.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/index'>;
}
declare module 'vue-loader/lib/style-compiler/load-postcss-config.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/load-postcss-config'>;
}
declare module 'vue-loader/lib/style-compiler/plugins/scope-id.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/plugins/scope-id'>;
}
declare module 'vue-loader/lib/style-compiler/plugins/trim.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/plugins/trim'>;
}
declare module 'vue-loader/lib/template-compiler/index.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/index'>;
}
declare module 'vue-loader/lib/template-compiler/modules/transform-require.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/modules/transform-require'>;
}
declare module 'vue-loader/lib/template-compiler/preprocessor.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/preprocessor'>;
}
declare module 'vue-loader/lib/utils/gen-id.js' {
  declare module.exports: $Exports<'vue-loader/lib/utils/gen-id'>;
}
declare module 'vue-loader/lib/utils/normalize.js' {
  declare module.exports: $Exports<'vue-loader/lib/utils/normalize'>;
}
