// flow-typed signature: 7ac8cb2fe661c731f94f577832a05560
// flow-typed version: <<STUB>>/webdriver-client_v~1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webdriver-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'webdriver-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webdriver-client/lib/common/initDriver' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/desktop/chrome/index' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/desktop/electron/index' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/helper' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/android/index' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/android/login' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/android/native' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/android/webview' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/ios/index' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/ios/login' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/ios/native' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/mobile/ios/webview' {
  declare module.exports: any;
}

declare module 'webdriver-client/lib/webdriver-client' {
  declare module.exports: any;
}

declare module 'webdriver-client/test/webdriver-client.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webdriver-client/index' {
  declare module.exports: $Exports<'webdriver-client'>;
}
declare module 'webdriver-client/index.js' {
  declare module.exports: $Exports<'webdriver-client'>;
}
declare module 'webdriver-client/lib/common/initDriver.js' {
  declare module.exports: $Exports<'webdriver-client/lib/common/initDriver'>;
}
declare module 'webdriver-client/lib/desktop/chrome/index.js' {
  declare module.exports: $Exports<'webdriver-client/lib/desktop/chrome/index'>;
}
declare module 'webdriver-client/lib/desktop/electron/index.js' {
  declare module.exports: $Exports<'webdriver-client/lib/desktop/electron/index'>;
}
declare module 'webdriver-client/lib/helper.js' {
  declare module.exports: $Exports<'webdriver-client/lib/helper'>;
}
declare module 'webdriver-client/lib/mobile/android/index.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/android/index'>;
}
declare module 'webdriver-client/lib/mobile/android/login.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/android/login'>;
}
declare module 'webdriver-client/lib/mobile/android/native.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/android/native'>;
}
declare module 'webdriver-client/lib/mobile/android/webview.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/android/webview'>;
}
declare module 'webdriver-client/lib/mobile/ios/index.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/ios/index'>;
}
declare module 'webdriver-client/lib/mobile/ios/login.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/ios/login'>;
}
declare module 'webdriver-client/lib/mobile/ios/native.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/ios/native'>;
}
declare module 'webdriver-client/lib/mobile/ios/webview.js' {
  declare module.exports: $Exports<'webdriver-client/lib/mobile/ios/webview'>;
}
declare module 'webdriver-client/lib/webdriver-client.js' {
  declare module.exports: $Exports<'webdriver-client/lib/webdriver-client'>;
}
declare module 'webdriver-client/test/webdriver-client.test.js' {
  declare module.exports: $Exports<'webdriver-client/test/webdriver-client.test'>;
}
