// flow-typed signature: 4392dc560809ad144be63641bda4cc97
// flow-typed version: <<STUB>>/weex-rax-framework_v0.1.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'weex-rax-framework'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'weex-rax-framework' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'weex-rax-framework/dist/framework.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/builtin' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/define.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/downgrade.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/emitter' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/fetch.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/index' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/require.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/semver' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/lib/timer.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/__tests__/index' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/builtin' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/define.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/downgrade.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/emitter' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/fetch.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/index' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/require.weex' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/semver' {
  declare module.exports: any;
}

declare module 'weex-rax-framework/src/timer.weex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'weex-rax-framework/dist/framework.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/dist/framework.weex'>;
}
declare module 'weex-rax-framework/lib/builtin.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/builtin'>;
}
declare module 'weex-rax-framework/lib/define.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/define.weex'>;
}
declare module 'weex-rax-framework/lib/downgrade.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/downgrade.weex'>;
}
declare module 'weex-rax-framework/lib/emitter.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/emitter'>;
}
declare module 'weex-rax-framework/lib/fetch.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/fetch.weex'>;
}
declare module 'weex-rax-framework/lib/index.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/index'>;
}
declare module 'weex-rax-framework/lib/require.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/require.weex'>;
}
declare module 'weex-rax-framework/lib/semver.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/semver'>;
}
declare module 'weex-rax-framework/lib/timer.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/lib/timer.weex'>;
}
declare module 'weex-rax-framework/src/__tests__/index.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/__tests__/index'>;
}
declare module 'weex-rax-framework/src/builtin.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/builtin'>;
}
declare module 'weex-rax-framework/src/define.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/define.weex'>;
}
declare module 'weex-rax-framework/src/downgrade.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/downgrade.weex'>;
}
declare module 'weex-rax-framework/src/emitter.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/emitter'>;
}
declare module 'weex-rax-framework/src/fetch.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/fetch.weex'>;
}
declare module 'weex-rax-framework/src/index.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/index'>;
}
declare module 'weex-rax-framework/src/require.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/require.weex'>;
}
declare module 'weex-rax-framework/src/semver.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/semver'>;
}
declare module 'weex-rax-framework/src/timer.weex.js' {
  declare module.exports: $Exports<'weex-rax-framework/src/timer.weex'>;
}
