// flow-typed signature: bb6805e77c077ed3ae6a0e2af1b8ea56
// flow-typed version: <<STUB>>/wwp_v^0.3.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wwp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wwp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wwp/lib/index' {
  declare module.exports: any;
}

declare module 'wwp/lib/log' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wwp/lib/index.js' {
  declare module.exports: $Exports<'wwp/lib/index'>;
}
declare module 'wwp/lib/log.js' {
  declare module.exports: $Exports<'wwp/lib/log'>;
}
