var RootComponent = require('./root')
var Container = require('./container')
var Image = require('./image')
var Text = require('./text')
var List = require('./list')
var Countdown = require('./countdown')
var Marquee = require('./marquee')
var Slider = require('./slider')
var Indicator = require('./indicator')
var Tabheader = require('./tabheader')
var Scroller = require('./scroller')
var Input = require('./input')
var Select = require('./select')
var Datepicker = require('./datepicker')
var Timepicker = require('./timepicker')
var Video = require('./video')
var Switch = require('./switch')
var A = require('./a')
var Embed = require('./embed')

var components = {
  init: function (Weex) {
    Weex.registerComponent('root', RootComponent)
    Weex.registerComponent('root', RootComponent)
    Weex.registerComponent('container', Container)
    Weex.registerComponent('image', Image)
    Weex.registerComponent('text', Text)
    Weex.registerComponent('list', List)
    Weex.registerComponent('countdown', Countdown)
    Weex.registerComponent('marquee', Marquee)
    Weex.registerComponent('slider', Slider)
    Weex.registerComponent('indicator', Indicator)
    Weex.registerComponent('tabheader', Tabheader)
    Weex.registerComponent('scroller', Scroller)
    Weex.registerComponent('input', Input)
    Weex.registerComponent('select', Select)
    Weex.registerComponent('datepicker', Datepicker)
    Weex.registerComponent('timepicker', Timepicker)
    Weex.registerComponent('video', Video)
    Weex.registerComponent('switch', Switch)
    Weex.registerComponent('a', A)
    Weex.registerComponent('embed', Embed)
  }
}

module.exports = components