const RootComponent = require('./root')
const Container = require('./container')
const Image = require('./image')
const Text = require('./text')
const Vlist = require('./vlist')
const Hlist = require('./hlist')
const Countdown = require('./countdown')
const Marquee = require('./marquee')
const Slider = require('./slider')
const Indicator = require('./indicator')
const Tabheader = require('./tabheader')
const Scroller = require('./scroller')
const Input = require('./input')
const Select = require('./select')
const Datepicker = require('./datepicker')
const Timepicker = require('./timepicker')
const Video = require('./video')
const Switch = require('./switch')
const A = require('./a')
const Embed = require('./embed')
const Refresh = require('./refresh')
const Loading = require('./loading')
const Spinner = require('./spinner')
const Web = require('./web')

const components = {
  init: function (Weex) {
    Weex.registerComponent('root', RootComponent)
    Weex.registerComponent('container', Container)
    Weex.registerComponent('div', Container)
    Weex.registerComponent('image', Image)
    Weex.registerComponent('text', Text)
    Weex.registerComponent('list', Vlist)
    Weex.registerComponent('vlist', Vlist)
    Weex.registerComponent('hlist', Hlist)
    Weex.registerComponent('countdown', Countdown)
    Weex.registerComponent('marquee', Marquee)
    Weex.registerComponent('slider', Slider)
    Weex.registerComponent('indicator', Indicator)
    Weex.registerComponent('tabheader', Tabheader)
    Weex.registerComponent('scroller', Scroller)
    Weex.registerComponent('input', Input)
    Weex.registerComponent('select', Select)
    Weex.registerComponent('datepicker', Datepicker)
    Weex.registerComponent('timepicker', Timepicker)
    Weex.registerComponent('video', Video)
    Weex.registerComponent('switch', Switch)
    Weex.registerComponent('a', A)
    Weex.registerComponent('embed', Embed)
    Weex.registerComponent('refresh', Refresh)
    Weex.registerComponent('loading', Loading)
    Weex.registerComponent('spinner', Spinner)
    Weex.registerComponent('loading-indicator', Spinner)
    Weex.registerComponent('web', Web)
  }
}

module.exports = components
