#ifndef IPCMESSAGEJS_H
#define IPCMESSAGEJS_H

enum class IPCJSMsg {
    INITFRAMEWORK,
    EXECJSSERVICE,
    TAKEHEAPSNAPSHOT,
    EXECJS,
	CREATEINSTANCE,
    DESTORYINSTANCE,
    EXECJSONINSTANCE,
    EXECJSWITHRESULT,
    UPDATEGLOBALCONFIG,
    EXECTIMERCALLBACK,
	INITAPPFRAMEWORK,
    CREATEAPPCONTEXT,
    EXECJSONAPPWITHRESULT,
    CALLJSONAPPCONTEXT,
    DESTORYAPPCONTEXT,
};

enum class IPCProxyMsg {
    SETJSFVERSION,
    REPORTEXCEPTION,
    CALLNATIVE,
    CALLNATIVEMODULE,
    CALLNATIVECOMPONENT,
    CALLADDELEMENT,
    SETTIMEOUT,
    NATIVELOG,
    CALLCREATEBODY,
    CALLUPDATEFINISH,
    CALLCREATEFINISH,
    CALLREFRESHFINISH,
    CALLUPDATEATTRS,
    CALLUPDATESTYLE,
    CALLREMOVEELEMENT,
    CALLMOVEELEMENT,
    CALLADDEVENT,
    CALLREMOVEEVENT,
    CALLGCANVASLINK,
	CALLT3DLINK,
    SETINTERVAL,
    CLEARINTERVAL,
	POSTMESSAGE,
  	DISPATCHMESSAGE,
};
#endif /* IPCMESSAGEJS_H */
